# Generated by Django 4.2.5 on 2023-09-19 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("celular", models.CharField(max_length=15)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("status", models.CharField(max_length=20)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Venture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(unique=True)),
                ("productTitle", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Programmer",
        ),
        migrations.AddField(
            model_name="cita",
            name="venture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.venture"
            ),
        ),
    ]
